{
  "phases": {
    "setup": {
      "nixPkgs": ["python3", "gcc"]
    },
    "install": {
      "cmds": [
        "python -m venv --copies /opt/venv",
        ". /opt/venv/bin/activate && pip install -r requirements.txt"
      ]
    },
    "build": {
      "cmds": []
    }
  },
  "start": {
    "cmd": "bash start-railway.sh"
  }
}
