name: Deploy to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy project to Oracle VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 84.235.175.123
          username: ubuntu
          key: ${{ secrets.ORACLE_SSH_KEY }}
          source: "housing-deployment"
          target: "/opt/housing-predictor"

      - name: Deploy on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 84.235.175.123
          username: ubuntu
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd /opt/housing-predictor/housing-deployment

            docker-compose down --remove-orphans || true
            docker system prune -af || true
            docker-compose build --no-cache
            docker-compose up -d
